In [1]:
import numpy as np

In [ ]:
# Scalar arithmetic
array = np.array([1, 2, 3])
print(array + 1)
print(array - 2)
print(array * 2)
print(array / 2)
print(array ** 2)

[2 3 4]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]


In [ ]:
# Vertorized math funcs
array = np.array([1.01, 2.5, 3.99])
print(np.sqrt(array))
print(np.round(array))
print(np.pi)

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
3.141592653589793


In [9]:
# EXERCISE
radii = np.array([1, 2, 3])
print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [12]:
# Elemet-wise arithmetic
array0 = np.array([1, 2, 3])
array1 = np.array([4, 5, 6])
print(array0 + array1)
print(array0 - array1)
print(array0 * array1)
print(array0 / array1)
print(array0 ** array1)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [16]:
# Comparison operators
scores = np.array([91, 55, 100, 73, 83, 74])
print(scores == 100)
print(scores >= 60)
print(scores < 60)

scores[scores < 60] = 0
print(scores)

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]
[ 91   0 100  73  83  74]
