In [1]:
import numpy as np

In [7]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18]
adults = ages[ages >= 18 & (ages < 65)]
seniors = ages[ages >= 65]
evens = ages[ages % 2 == 0]
odds = ages[ages % 2 != 0]
print(teenagers)
print(adults)
print(seniors)
print(evens)
print(odds)

[17 16 15]
[21 17 19 20 16 30 18 65 39 22 15 99 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]


In [10]:
adults = np.where(ages >= 18, ages, -1)

print(adults)

[[21 -1 19 20 -1 30 18 65]
 [39 22 -1 99 18 19 20 21]]
