In [1]:
import numpy as np

In [32]:
# 마크랑 똑같이 시드가 같으면 같은 수가 나옴 
rng = np.random.default_rng()

# 정수
print(rng.integers(1, 7, size=(2, 10)))

# uniform, uniform distribution
print(rng.uniform(-1, 7, size=(2, 10)))

# Shuffle
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)

# Choice
fruits = np.array(["apple", "orange", "banana", "coconut", "pineapple"])
fruit = rng.choice(fruits, size=3)
print(fruit)
fruit = rng.choice(fruits, size=(3, 3))
print(fruit)

[[4 6 5 2 6 5 4 5 6 2]
 [5 1 3 3 2 1 5 6 2 5]]
[[ 2.76883643 -0.79616143  1.42255355  1.14251642  6.62634596  6.07293101
   3.14022723  3.34805891 -0.37952442  4.57144182]
 [ 2.66078127  4.72667937  6.84819337  0.22987891  4.13050635 -0.27600652
   3.55408952  6.15229343  2.090562    4.70358302]]
[5 1 2 3 4]
['pineapple' 'orange' 'orange']
[['pineapple' 'banana' 'pineapple']
 ['pineapple' 'coconut' 'coconut']
 ['banana' 'orange' 'pineapple']]
