In [1]:
import numpy as np

In [ ]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7 , 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

# Slicing method
# 1. array[start:end:step]
print(array[0:4:2])
print(array[::-1])

# 2. array[rows, columns]
#    array[start:end:step, start:end:step]
print(array[::, ::])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
